from __future__ import annotations

from pathlib import Path

from tools.install_sandbox.reference_resolution import PackagedReferenceResolution
from tools.install_sandbox.surfaces import install_surface_generated
from tools.install_sandbox.surfaces import install_surface_models
from tools.install_sandbox.surfaces import install_surface_state
from tools.install_sandbox.surfaces import install_surface_statuses
from tools.install_sandbox.targets import install_target_models
from tools.install_sandbox.surfaces.install_surface_models import InstallSurface


def resolution(status: str, names: tuple[str, ...] = (), detail: str = "test detail") -> PackagedReferenceResolution:
    return PackagedReferenceResolution(status, expected_names=names, detail=detail)


def expected_skill(root: str, relative: str) -> InstallSurface:
    return InstallSurface(root, relative, skill_sidecar_expectation=install_surface_models.SkillSidecarExpectation())


def test_install_surface_generated_classifies_generated_file_relevance_decisions() -> None:
    skill_entry = expected_skill("home", ".codex/skills/graphify/SKILL.md")
    ordinary_entry = InstallSurface("project", "AGENTS.md")
    expected = (skill_entry, ordinary_entry)
    expectation = install_target_models.GeneratedFileExpectation(
        relative_substrings=("graphify",),
        text_suffixes=(".md",),
        content_markers=("Graphify",),
        include_user_content_sentinel=True,
        max_text_bytes=12,
    )

    assert install_surface_state.expected_generated_relative_keys(expected, resolution("available", ("query.md",))) == {
        ("home", ".codex/skills/graphify/SKILL.md"),
        ("home", ".codex/skills/graphify/.graphify_version"),
        ("home", ".codex/skills/graphify/references.tmp"),
        ("home", ".codex/skills/graphify/references"),
        ("home", ".codex/skills/graphify/references/query.md"),
        ("project", "AGENTS.md"),
    }
    assert install_surface_generated.is_excluded_generated_path(Path(".local/lib/example.py"), (".local", ".cache", "__pycache__", ".pytest_cache")) is True
    assert install_surface_generated.is_expected_generated_key(expected, "project", Path("AGENTS.md")) is True
    assert install_surface_generated.is_skill_sidecar_relative(expected, "home", Path(".codex/skills/graphify/references/nested/query.md")) is True
    assert install_surface_generated.is_small_text_candidate(expectation, file_size=12, suffix=".md") is True
    assert install_surface_generated.is_small_text_candidate(expectation, file_size=13, suffix=".md") is False
    assert install_surface_generated.is_small_text_candidate(expectation, file_size=12, suffix=".bin") is False
    assert install_surface_generated.text_mentions_expected_generated_marker(expectation, "generated by graphify") is True
    assert install_surface_generated.text_mentions_expected_generated_marker(expectation, install_surface_state.USER_SENTINEL) is True

    candidate = install_surface_generated.generated_file_observation(
        expectation,
        expected,
        "project",
        Path("notes.md"),
        file_size=12,
        mentions_expected_marker=False,
        excluded_path=False,
    )
    assert candidate.root_name == "project"
    assert candidate.relative == Path("notes.md")
    assert candidate.suffix == ".md"
    assert candidate.file_size == 12
    assert candidate.expected_key is False
    assert candidate.skill_sidecar_relative is False
    assert candidate.excluded_path is False
    assert candidate.relative_substring_match is False
    assert candidate.small_text_candidate is True
    assert candidate.needs_text_marker_match is True
    assert install_surface_generated.decide_generated_file_observation(candidate).should_include is False

    marker_match = install_surface_generated.generated_file_observation(
        expectation,
        expected,
        "project",
        Path("notes.md"),
        file_size=12,
        mentions_expected_marker=True,
        excluded_path=False,
    )
    marker_decision = install_surface_generated.decide_generated_file_observation(marker_match)
    assert marker_decision.is_relevant is True
    assert marker_decision.is_ignored is False
    assert marker_decision.should_include is True

    excluded = install_surface_generated.generated_file_observation(
        expectation,
        expected,
        "project",
        Path(".cache/graphify.txt"),
        file_size=12,
        mentions_expected_marker=True,
        excluded_path=True,
    )
    excluded_decision = install_surface_generated.decide_generated_file_observation(excluded)
    assert excluded.path_relevant is True
    assert excluded.needs_text_marker_match is False
    assert excluded_decision.is_relevant is True
    assert excluded_decision.is_ignored is True
    assert excluded_decision.should_include is False

    assert (
        install_surface_generated.is_relevant_generated_file(
            expectation,
            expected,
            "project",
            Path("AGENTS.md"),
            small_text_candidate=False,
            mentions_expected_marker=False,
        )
        is True
    )
    assert (
        install_surface_generated.is_relevant_generated_file(
            expectation,
            expected,
            "home",
            Path(".codex/skills/graphify/.graphify_version"),
            small_text_candidate=False,
            mentions_expected_marker=False,
        )
        is True
    )
    assert (
        install_surface_generated.is_relevant_generated_file(
            expectation,
            expected,
            "project",
            Path("notes/graphify-log.bin"),
            small_text_candidate=False,
            mentions_expected_marker=False,
        )
        is True
    )
    assert (
        install_surface_generated.is_relevant_generated_file(
            expectation,
            expected,
            "project",
            Path("notes.md"),
            small_text_candidate=True,
            mentions_expected_marker=True,
        )
        is True
    )
    assert (
        install_surface_generated.is_relevant_generated_file(
            expectation,
            expected,
            "project",
            Path("notes.md"),
            small_text_candidate=True,
            mentions_expected_marker=False,
        )
        is False
    )
    assert (
        install_surface_generated.is_relevant_generated_file(
            expectation,
            expected,
            "project",
            Path("notes.md"),
            small_text_candidate=False,
            mentions_expected_marker=True,
        )
        is False
    )


def test_install_surface_generated_derives_generated_artifact_copy_destination() -> None:
    plan = install_surface_generated.generated_artifact_copy_plan(
        "project",
        Path("nested/graphify-output.txt"),
    )

    assert plan == install_surface_generated.GeneratedArtifactCopyPlan(
        root_name="project",
        source_relative=Path("nested/graphify-output.txt"),
        destination_relative=Path("project/nested/graphify-output.txt"),
    )


def test_install_surface_statuses_decides_file_fingerprint_from_observed_facts() -> None:
    notes_text = f"# Notes\n\n{install_surface_state.USER_SENTINEL}\n\n## graphify\n{install_surface_state.STALE_GRAPHIFY_SENTINEL}\n"

    assert install_surface_statuses.file_fingerprint_from_observation(
        install_surface_statuses.FileFingerprintObservation(exists=False)
    ) == {"exists": False}
    assert install_surface_statuses.file_fingerprint_from_observation(
        install_surface_statuses.FileFingerprintObservation(exists=True, kind="dir")
    ) == {"exists": True, "kind": "dir"}

    fingerprint = install_surface_statuses.file_fingerprint_from_observation(
        install_surface_statuses.FileFingerprintObservation(
            exists=True,
            kind="file",
            data=notes_text.encode("utf-8"),
            text=notes_text,
        ),
        "## graphify",
        install_surface_models.TextExpectation(preserve_user_content=True, repair_stale_graphify_section=True),
    )

    assert fingerprint["exists"] is True
    assert fingerprint["kind"] == "file"
    assert fingerprint["size"] == len(notes_text.encode("utf-8"))
    assert fingerprint["marker_count"] == 1
    assert fingerprint["user_content_preserved"] is True
    assert fingerprint["stale_graphify_present"] is True
    assert isinstance(fingerprint["sha256"], str)
