target-version = "py312"
line-length = 100
preview = false

[lint]
select = ["E", "F", "I", "UP", "B", "SIM", "RUF", "C901", "PLR0912", "PLR0915"]

[lint.mccabe]
max-complexity = 8

[lint.pylint]
max-branches = 10
max-statements = 30
