from __future__ import annotations

try:
    from .install_target_models import (
        GRAPHIFY_MARKER,
        MIXED_SCOPE_GLOBAL_SKILL_PROJECT_WIRING_NOTE,
        MIXED_SCOPE_PROJECT_WIRING_NOTE,
        PUBLIC_CLI_LACKS_USER_SKILL_UNINSTALL_NOTE,
        SIMULATED_LINUX_LAYOUT_NOTE,
        DisposableArtifactScenarioSpec,
        DisposableSeedFile,
        ExpectedPath,
        FileEffect,
        GeneratedFileExpectation,
        InstallCommandVariant,
        InstallTargetSpec,
        InstallSurface,
        JsonExpectation,
        JsonHookExpectation,
        JsonHooksEffect,
        JsonPluginEffect,
        JsonPluginExpectation,
        PlatformSpec,
        ReferenceBundle,
        Scenario,
        ScopeSpec,
        SelectedUniversalUninstallScenario,
        SkillEffect,
        SkillSidecarExpectation,
        TargetRuntimeValidationSpec,
        TextExpectation,
        TextSectionEffect,
        UniversalUninstallScenarioSpec,
    )
    from .install_target_catalog import (
        InstallTargetCatalog,
        ScenarioRegistry,
        _declared_install_variants,
        _dedupe_notes,
        _direct_project_install,
        _generic_install_command,
        _generic_uninstall_command,
        _scenario,
        _skill,
    )
    from . import install_target_defaults as _install_target_defaults
    from .install_target_defaults import (
        _LAZY_DEFAULT_NAMES,
        default_install_target_catalog,
        direct_install_command,
        direct_uninstall_command,
        disposable_artifact_scenarios,
        equivalence_status,
        equivalent_install_command,
        equivalent_install_variants,
        generic_install_command,
        install_target_scenarios,
        install_target_spec,
        install_target_specs,
        make_scenario,
        platform_scenarios,
        platform_spec,
        project_skill,
        risk_notes,
        sandbox_platform_specs,
        target_runtime_validation_sections,
        universal_uninstall_scenarios,
        unsupported_scope_reason,
        user_skill,
        validate_roots,
    )
except ImportError:  # pragma: no cover - direct script import fallback
    from install_target_models import (  # type: ignore[no-redef]
        GRAPHIFY_MARKER,
        MIXED_SCOPE_GLOBAL_SKILL_PROJECT_WIRING_NOTE,
        MIXED_SCOPE_PROJECT_WIRING_NOTE,
        PUBLIC_CLI_LACKS_USER_SKILL_UNINSTALL_NOTE,
        SIMULATED_LINUX_LAYOUT_NOTE,
        DisposableArtifactScenarioSpec,
        DisposableSeedFile,
        ExpectedPath,
        FileEffect,
        GeneratedFileExpectation,
        InstallCommandVariant,
        InstallTargetSpec,
        InstallSurface,
        JsonExpectation,
        JsonHookExpectation,
        JsonHooksEffect,
        JsonPluginEffect,
        JsonPluginExpectation,
        PlatformSpec,
        ReferenceBundle,
        Scenario,
        ScopeSpec,
        SelectedUniversalUninstallScenario,
        SkillEffect,
        SkillSidecarExpectation,
        TargetRuntimeValidationSpec,
        TextExpectation,
        TextSectionEffect,
        UniversalUninstallScenarioSpec,
    )
    from install_target_catalog import (  # type: ignore[no-redef]
        InstallTargetCatalog,
        ScenarioRegistry,
        _declared_install_variants,
        _dedupe_notes,
        _direct_project_install,
        _generic_install_command,
        _generic_uninstall_command,
        _scenario,
        _skill,
    )
    import install_target_defaults as _install_target_defaults  # type: ignore[no-redef]
    from install_target_defaults import (  # type: ignore[no-redef]
        _LAZY_DEFAULT_NAMES,
        default_install_target_catalog,
        direct_install_command,
        direct_uninstall_command,
        disposable_artifact_scenarios,
        equivalence_status,
        equivalent_install_command,
        equivalent_install_variants,
        generic_install_command,
        install_target_scenarios,
        install_target_spec,
        install_target_specs,
        make_scenario,
        platform_scenarios,
        platform_spec,
        project_skill,
        risk_notes,
        sandbox_platform_specs,
        target_runtime_validation_sections,
        universal_uninstall_scenarios,
        unsupported_scope_reason,
        user_skill,
        validate_roots,
    )


def __getattr__(name: str):
    if name in _LAZY_DEFAULT_NAMES:
        value = getattr(_install_target_defaults, name)
        globals()[name] = value
        return value
    raise AttributeError(name)
